spring:
  profiles:
    group:
      "local":"common","local_env"
---
spring:
  profiles:
    group:
      "dev":"common","local_dev"
---
spring:
  profiles:
    group:
      "prod":"common","local_prod"
---
spring:
  config:
    activate:
      on-profile: "common"
---
spring:
  config:
    activate:
      on-profile: "local_env"
---
spring:
  config:
    activate:
      on-profile: "dev_env"
server:
  port: 80
---
spring:
  config:
    activate:
      on-profile: "prod_env"
server:
  port: 80
